### ISSUE TITLE
Opening database failed

### ISSUE THREAD

**Issue by ipa-hsd** [BerkeleyAutomation/dex-net#5] opened 2017-10-24 11:24 UTC
I downloaded the [hdf5 databases](https://berkeley.app.box.com/s/jnbwcj3zppcdhg5ffgf47ugqngosm40g/folder/31861931687) and used the command 

    cat hdf5.dexnet_2_database_parta* > dexnet_2_database.hdf5

But I get the error while running the Dex-Net CLI

    Opening database failed: Can't determine (bad symbol table node signature) 

It was the same case even with `example.hdf5`. The only db I was able to open was `test.hdf5` available in the github repo, which was empty. How can I get it to work?

**Comment by jeffmahler** [comment] 2017-10-24 17:47
The error message means that your database is corrupt. We have seen this issue come up before and the only solution we know of is to re-download and re-cat the database. Can you give this a try? In the meantime I will double-check the file on Box.

**Comment by ipa-nhg-hd** [comment] 2017-10-25 06:45
Is it not possible to break them down to smaller chunks? The download fails most of the time because of the large size. Maybe I could write a script to download all the smaller chunks and cat them.

**Comment by ipa-nhg-hd** [comment] 2017-10-26 15:38
I tried downloading it again, but this time I got an error 

`Opening database failed: Can't determine (wrong B-tree signature)`

I tried the following code: 
```
import h5py
filename = 'dexnet_2_database.hdf5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
# output: Keys: [u'datasets', u'mydataset']
a_group_key = f.keys()[0]

# Get the data
data = list(f[a_group_key])
print data
# ouput: [u'3dnet', u'kit']
```

So I am guessing the DB is fine this time, but is not being read properly by the CLI?

**Comment by Qidian213** [comment] 2017-11-01 07:00
Hi , Is your problem solved?  We also encountered this problem .

**Comment by ipa-nhg-hd** [comment] 2017-11-01 18:06
Not yet. Still the same issue

**Comment by jeffmahler** [comment] 2017-11-05 22:52
Apologies for the delay. I have been traveling and I'm the only one with access to the public data repo. We have a new database that shouldn't need to be stitched together from two pieces that I'll upload tomorrow.

**Comment by jeffmahler** [comment] 2017-11-06 20:00
The database is now uploaded as a single file (here)[https://berkeley.box.com/s/whemgcmik55qoriggm25g427kh8m2q0q]. It opens on my machine. Can one of you try it out and let me know how it goes?

**Comment by jl1914** [comment] 2017-11-10 06:34
I came across similar problem. Luckily after re-downloading the 2 files many many times, the database can be opened normally. The unstable and slow internet suspected culprit.

I think it will be better to attach MD5 to large files. 

In addition, compared with a single large file, people with a bad internet connection might prefer several small ones.

**Comment by jeffmahler** [comment] 2017-11-11 18:39
Thank you, and sorry for the issues. I like the checksum idea and we will look into that. I will update this thread when we find a new solution.

**Comment by jeffmahler** [comment] 2017-11-15 22:41
I just uploaded an MD5 checksum file with an updated README. We are working toward a new, smaller version of the database to help mitigate these issues in the future.

**Comment by ipa-nhg-hd** [comment] 2017-11-16 08:26
Have you seen [this](https://support.hdfgroup.org/projects/hdfserver/)? I can access the server within the LAN, but not sure how to host this on the Internet.

**Comment by Qidian213** [comment] 2017-11-16 13:55
We had reproduced GQ-CNN successfully and it meets our requirements , so we gave up this project.

**Comment by jeffmahler** [comment] 2017-11-27 01:57
@ipa-nhg-hd Thank you very much for the suggestion. We are currently looking into h5serv. In the past we didn't use it because it mirrors the entire database tree using hdf5 references which was not very efficient.

We also have an initial version of an HTTP API but that is not quite ready to share. Stay tuned!

**Comment by jeffmahler** [comment] 2018-01-08 17:00
Hi everyone,  I revisited this issue and found that Box has a direct download link that seems to be more reliable when run from the command line. On a Unix system you can download the database using the command:
`wget https://berkeley.box.com/shared/static/whemgcmik55qoriggm25g427kh8m2q0q.hdf5`

You can verify the download by comparing against [this checksum](https://berkeley.box.com/s/spmpyn8tuu8gvvnnes8ci0cychpil2xw).

**Comment by jeffmahler** [comment] 2018-02-13 17:57
If anyone is still having issues with this, then I suggest using the [download shell script.](https://berkeley.box.com/s/skv5hs7oi9ggurnlqkqiyixrjndfscvz). I've added this to the scripts repo of the master branch as well.

**Comment by ipa-nhg-hd** [comment] 2018-02-26 09:46
Thanks for the link @jeffmahler ! The download works very well now :)
But I am still having issues with rendering. This is the error I get after starting the python client:

```
Unable to import meshrender shared library! Rendering will not work. Likely due to missing Boost.Numpy
Boost.Numpy can be installed following the instructions in https://github.com/ndarray/Boost.NumPy
```

**Comment by jeffmahler** [comment] 2018-02-26 18:04
@ipa-nhg-hd Did you install Boost.Numpy and get an installation error? I understand that newer versions of boost can cause problems....

BTW, we are have a new version of the renderer [here](https://github.com/BerkeleyAutomation/meshrender) but the current dex-net repo doesn't support it. The next release will!

**Comment by jeffmahler** [comment] 2018-11-16 07:05
Closing. The original issue was fixed per https://github.com/BerkeleyAutomation/dex-net/issues/5#issuecomment-365349774

**Closed by jeffmahler** 2018-11-16 07:05 UTC

**Comment by jzhang2008** [comment] 2019-07-26 10:58
Hi @jeffmahler I also have the same problem, you think that the newer versions of boost can cause these problem. which version of boost is more suitable?
